<?php





/**
* Random functions can be placed here
*/


/**
* Add block with slider for front of website
*/

// TODO: Create block, add images to site
/**
 * Implementation of hook_block_info().
 */
function uprise_misc_functions_block_info() {
  $blocks['uprise_home_slider'] = array(
    'info' => t('Uprise home slider'),
  );
  return $blocks;
}
 
/**
 * Implementation of hook_block_view().
 */
function uprise_misc_functions_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'uprise_home_slider':
      $block['subject'] = '';
      $block['content'] = uprise_home_slider_contents();
      break;
  }
  return $block;
}
 
/**
 * custom html block
 * @return string
 */
function uprise_home_slider_contents() {
   
            
            
    
  return
  '
  <style>

		#back_to_camera {
			clear: both;
			display: block;
			height: 80px;
			line-height: 40px;
			padding: 20px;
		}
		.fluid_container {
			margin: 0 auto;
			max-width: 1000px;
			width: 90%;
		}
	</style>
        
        <script>
		jQuery(function(){
			
			jQuery("#camera_wrap_1").camera({
				thumbnails: true
			});
		});
	</script>
  
    <div class="fluid_container">

        <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
            <div data-thumb="/sites/default/files/slides/thumbs/0_butterfly.jpg" data-src="/sites/default/files/slides/0_butterfly.jpg">
                <div class="camera_caption fadeFromBottom">
                    Start your revolution. <a href="/user/register">Join us!</a>
		</div>
            </div>
            <div data-thumb="/sites/default/files/slides/thumbs/1_hero.jpg" data-src="/sites/default/files/slides/1_hero.jpg">
                <div class="camera_caption fadeFromBottom">
                    Get inspired. <a href="/user/register">Join us!</a>
                </div>
            </div>
            <div data-thumb="/sites/default/files/slides/thumbs/2_rocketeer.jpg" data-src="/sites/default/files/slides/2_rocketeer.jpg">
                <div class="camera_caption fadeFromBottom">
                    For life above average. <a href="/user/register">Join us!</a>
                </div>
            </div>
            <div data-thumb="/sites/default/files/slides/thumbs/3_angel.jpg" data-src="/sites/default/files/slides/3_angel.jpg">
                <div class="camera_caption fadeFromBottom">
                    Help us spread inspiration. <a href="/user/register">Join us!</a>
                </div>                                                                
            </div>
            <div data-thumb="/sites/default/files/slides/thumbs/4_combined.jpg" data-src="/sites/default/files/slides/4_combined.jpg">
                <div class="camera_caption fadeFromBottom">
                    Start your upRise. <a href="/user/register">Join us!</a>
                </div>                                                                
            </div>
        </div><!-- #camera_wrap_1 -->


    </div><!-- .fluid_container -->

        
  ';
}